# Generated by Django 4.2.7 on 2025-07-30 18:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerate',
            name='spread',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.01'), max_digits=5),
        ),
    ]
