# Generated by Django 4.2.7 on 2025-07-31 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_exchangerate_date'),
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyconversion',
            name='from_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_conversion_from', to='core.currency'),
        ),
        migrations.AlterField(
            model_name='currencyconversion',
            name='to_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_conversion_to', to='core.currency'),
        ),
    ]
