# Generated by Django 4.2.7 on 2025-08-01 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_tenant_user_otp_user_tenant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenant',
            options={'ordering': ['id'], 'verbose_name_plural': 'tenant'},
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='tenant_id',
        ),
        migrations.AddField(
            model_name='tenant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
