# Generated by Django 4.2.7 on 2025-08-01 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_tenant_options_remove_tenant_tenant_id_and_more'),
    ]

    operations = [

    ]
